<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="ResourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="color"/>
            <xs:enumeration value="depth"/>
            <xs:enumeration value="final"/>
            <xs:enumeration value="normal"/>
            <xs:enumeration value="position"/>
            <xs:enumeration value="material"/>
            <xs:enumeration value="ssao"/>
            <xs:enumeration value="shadow_visibility"/>
            <xs:enumeration value="shadow_depth"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PassType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="preprocess::depth"/>
            <xs:enumeration value="preprocess::ssao"/>
            <xs:enumeration value="preprocess::ssao_blur"/>
            <xs:enumeration value="forward"/>
            <xs:enumeration value="deferred::geometry"/>
            <xs:enumeration value="deferred::composition"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ResourceUsage">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ColorAttachmentWrite"/>
            <xs:enumeration value="DepthStencilAttachmentWrite"/>
            <xs:enumeration value="DepthStencilAttachmentRead"/>
            <xs:enumeration value="SampledFragment"/>
            <xs:enumeration value="StorageComputeWrite"/>
            <xs:enumeration value="TransferSrc"/>
            <xs:enumeration value="TransferDst"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="rendergraph">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="resource" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="type" type="ResourceType" use="required"/>

                        <xs:attribute name="width" type="xs:positiveInteger"/>
                        <xs:attribute name="height" type="xs:positiveInteger"/>

                        <xs:attribute name="scale">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.0"/>
                                    <xs:maxInclusive value="1.0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:assert test="
                            (
                                exists(@scale)
                                and not(exists(@width) or exists(@height))
                            )
                            or
                            (
                                exists(@width)
                                and exists(@height)
                                and not(exists(@scale))
                            )
                            or
                            (
                                not(exists(@scale))
                                and not(exists(@width))
                                and not(exists(@height))
                            )
                        "/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="pass" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="value" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="input" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="usage" type="ResourceUsage" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="usage" type="ResourceUsage" use="required"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="output" type="xs:IDREF" use="required"/>
            <xs:attribute name="profile" type="xs:string" use="required"/>

        </xs:complexType>
    </xs:element>

</xs:schema>